<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-7S66DHJU" failures="1" tests="2" name="Test(failed)" time="22.66" errors="0" timestamp="2024-04-20T18:41:26 IST">
  <testcase classname="testCases.TC_001_AccountRegistrationTest" name="verify_account_registration" time="6.269">
    <failure type="java.lang.AssertionError" message="expected [Your Account Has Been Created!Q!] but found [Your Account Has Been Created!]">
      <![CDATA[java.lang.AssertionError: expected [Your Account Has Been Created!Q!] but found [Your Account Has Been Created!]
at testCases.TC_001_AccountRegistrationTest.verify_account_registration(TC_001_AccountRegistrationTest.java:35)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- verify_account_registration -->
  <testcase classname="testCases.TC_002_LoginTest" name="verify_login" time="2.594"/>
</testsuite> <!-- Test(failed) -->
